# Generated by Django 5.2.7 on 2025-11-15 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_categoria_alter_tarea_options_tarea_fecha_completada_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarea',
            options={'ordering': ['-fecha_creacion']},
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='fecha_completada',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='tarea',
            name='estado',
            field=models.CharField(choices=[('pendiente', '📝 Pendiente'), ('en_progreso', '🔄 En Progreso'), ('completada', '✅ Completada')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='prioridad',
            field=models.CharField(choices=[('baja', '🟢 Baja'), ('media', '🟡 Media'), ('alta', '🔴 Alta')], default='media', max_length=20),
        ),
    ]
